### ISSUE TITLE
what does negative values in SSMs mean?

### ISSUE THREAD

**Issue by beantowel** [ctralie/GraphDitty#8]
I calculated 'Fused', 'MFCCs', 'Chromas' and 'Tempogram' matrices for a song, the result shows some of the SSMs has negative values, specifically, their minimums and maximums are:
```
Fused: 0.0 ~ 3.159
MFCCs: -0.054 ~ 1.000
Chromas: -0.105 ~ 1.000
Tempogram: 0.0 ~ 1.000
```
I wonder what the negative values mean in SSM, as i thougt the self-similarity metrics should be a positive value, ideally in range [0,1]. So what does negative values in SSMs mean, or is that a bug?

**Comment by ctralie** [comment]
Hello,
Thank you for bringing this to my attention!  That is disturbing, and
definitely more than just numerical precision.  At least the fused matrix
is in the correct range, but I will definitely check the others as soon as
possible

**Comment by ctralie** [comment]
By the way, it would be particularly helpful if you could attach the
features that lead to this happening, and to show me exactly where in the
execution you checked for those values

**Comment by beantowel** [comment]
Really sorry, i reproduced the case, and found it was my fault. The GraphDitty works well, it's because i used `from scipy.ndimage.interpolation import zoom` zoom to reduce the matrix size, and the interpolation caused the negative values. Anyway, thanks for your immediate reply.

**Comment by ctralie** [comment]
Okay that is a relief
